name: Build and upload staging website to stage S3 bucket

on:
  push:
    branches:
      - develop
    paths-ignore:
      - README.md
      - .gitignore
      - LICENSE
      - gen_post.sh

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true
      - name: Build Site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Cofnigure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "${{ secrets.AWS_GITHUB_ACTIONS_EXECUTION_ROLE }}"
          aws-region: us-east-1
      - name: Deploy to AWS S3
        run: |
          aws s3 sync ./_site/ s3://${{ secrets.STAGE_BUCKET_NAME }} --delete

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Create pull request
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          https://api.github.com/repos/octocat/${{ github.repository }}/pulls \
          -d '{"head": "develop", "base": "main"}'
