name: Build and upload site to prod S3 bucket

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true
      - name: Build Site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Cofnigure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "arn:aws:iam::649863256707:role/github-oidc-povider-GithubActionsExecutionRole-1N5M14XHC4QVL"
          aws-region: us-east-1
      - name: Deploy to AWS S3
        run: |
          aws s3 sync ./_site/ s3://www.aaronzhaocr.net --delete
